### ISSUE TITLE
legacy-editor: Sentry doesn't track legacy GeoGebra applets correctly

### ISSUE THREAD

**Issue by inyono** [serlo/athene2-assets#41]
Our tracking for legacy GeoGebra applets, https://github.com/serlo/athene2-assets/blob/f24b1ae7d170ee3978c681680304cee1b67cf97a/src/main/modules/injections.js#L190 doesn't work correctly. It (also or only?) tracks legacy image uploads which we don't care about.

**Comment by Knorrke** [comment]
Can you provide an article where this happens? I checked that log a few days back and did find legacy applets in the most often logged pages.... I think I already replaced one or two, maybe that's why it did look wrong to you?

**Comment by inyono** [comment]
You're right. Got baited by https://github.com/serlo/editor-plugins/issues/56 that has only legacy images in the "main" content but a legacy applet in one of the solutions.
