### ISSUE TITLE
editor: confirm delete

### ISSUE THREAD

**Issue by simonkoehl** [serlo/athene2-assets#44]
ask users if they are sure after clicking on delete button

**Comment by inyono** [comment]
Mh, not sold on this. Deleting an element is undoable (as pretty much any other action in the editor). So having a confirmation step is IMHO just noise. I’d prefer to present the undo/redo options more prominently instead.

**Comment by SimonKoehl** [comment]
Sure? Same functionality in Mailchimp editor:

![image](https://user-images.githubusercontent.com/3379377/51404751-a884f780-1b54-11e9-8bfd-82b63b91369a.png)

**Comment by inyono** [comment]
Pretty sure, but I can discuss that with Flo and/or Botho. Is this action undoable in MailChimp?

**Comment by SimonKoehl** [comment]
no, there is no way back in MailChimp after confirming the delete. Is there in our editor? strg-z didn't work..

**Comment by inyono** [comment]
Yep, there is. I can readd the Shortcuts and add buttons for that.

**Comment by inyono** [comment]
upstream issue: https://github.com/splish/editor/issues/16

**Comment by Knorrke** [comment]
Closing, because undo/redo is working for this use case in edtr.io and we have buttons on the page.
